### ISSUE TITLE
Snyk reports - Prototype Pollution for 4.0.0

### ISSUE THREAD

**Issue by yenanandu** [yargs/y18n#112]
Team - any plans to release a patch version for 4.0.0 to address below issue
https://snyk.io/vuln/SNYK-JS-Y18N-1021887

**Comment by KTOmega** [comment]
It seems like #108 (the fix for the vulnerability) should be fairly compatible with the 4.0.0 release, despite the different JavaScript languages used in the patch. There's no current branch for 4.0.0 releases at the moment, so would the y18n team be willing to publish a new version from the 4.0.0 branch?

**Comment by bcoe** [comment]
@KTOmega @yenanandu I have back-ported the patch.

**Comment by stof** [comment]
@bcoe given that gulp-cli still relies on the 3.x branch, woould you consider backporting it to a 3.2.2 release as well ?
