### ISSUE TITLE
TypeError: y18n.__ is not a function

### ISSUE THREAD

**Issue by uMtMu** [yargs/y18n#53]
Hi,
I'm trying to run your example on https://npm.runkit.com/y18n. I'm getting "TypeError: y18n.__ is not a function". My code is like below.

``` javascript
var y18n = require("y18n")

console.log(y18n.__('%s %s', '1111', '2222'))

```

I'm a newbie on JS and Nodejs. Can you help me?

**Comment by nexdrew** [comment]
@uMtMu Hi 👋

It's not quite clear in the documentation, but the main export of this module is a function rather than an instance/object. To get a usable `y18n` instance, you need to call this function and assign its return value to a variable.

Try this code instead:

```js
const Y18n = require('y18n')                  // Y18n is a function
const y18n = Y18n({ updateFiles: false })     // pass opts and get an instance
console.log(y18n.__('%s %s', '1111', '2222')) // now this works!
```

This could also be shortened to:

```js
const y18n = require('y18n')({ updateFiles: false })
console.log(y18n.__('%s %s', '1111', '2222'))
```

Hope this helps! Let us know if you have other questions, and thanks for trying out y18n.

**Comment by uMtMu** [comment]
It helps thank you. Maybe you should update README.md file.
